### ISSUE TITLE
Assertion Error with Glyphs file containing native color layers

### ISSUE THREAD

**Issue by SophiaDesign** [googlefonts/glyphsLib#1031]
I tried to export a TTF output which would make this a COLRv1 font: `fontmake Font.glyphs -o ttf`

```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.parser:Parsing .glyphs file
Traceback (most recent call last):
  File "/venv/bin/fontmake", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.10/site-packages/fontmake/__main__.py", line 656, in main
    project.run_from_glyphs(inputs.glyphs_path, **args)
  File "/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 823, in run_from_glyphs
    designspace_path = self.build_master_ufos(
  File "/venv/lib/python3.10/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 223, in build_master_ufos
    designspace = glyphsLib.to_designspace(
  File "/venv/lib/python3.10/site-packages/glyphsLib/builder/__init__.py", line 123, in to_designspace
    return builder.designspace
  File "/venv/lib/python3.10/site-packages/glyphsLib/builder/builders.py", line 325, in designspace
    list(self.masters)  # Make sure that the UFOs are built
  File "/venv/lib/python3.10/site-packages/glyphsLib/builder/builders.py", line 224, in masters
    self.to_ufo_color_layers(ufo, master)  # .color_layers
  File "/venv/lib/python3.10/site-packages/glyphsLib/builder/color_layers.py", line 234, in to_ufo_color_layers
    _to_ufo_color_layers(self, ufo, master, layerMapping)
  File "/venv/lib/python3.10/site-packages/glyphsLib/builder/color_layers.py", line 178, in _to_ufo_color_layers
    assert glyph.name not in layerMapping
AssertionError
```

**Comment by SophiaDesign** [comment]
@schriftgestalt Hi Georg, thought it might be worth mentioning to you as well, just in case. 
I am using Glyphs version 3.3 (3311).

**Comment by SophiaDesign** [comment]
Solved. Cannot have both `native color` and `colorPalette` layer attribute simultaneously.
