### ISSUE TITLE
Axis mappings may be strings instead of int

### ISSUE THREAD

**Issue by madig** [googlefonts/glyphsLib#527]
I got this traceback mailed to me:

```
Traceback (most recent call last):
  File "/Users/.../bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/Users/.../lib/python3.6/site-packages/fontmake/__main__.py", line 258, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/.../lib/python3.6/site-packages/fontmake/font_project.py", line 560, in run_from_glyphs
    mti_source=mti_source)
  File "/Users/.../lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/Users/.../lib/python3.6/site-packages/fontmake/font_project.py", line 131, in build_master_ufos
    font, family_name=family_name, instance_dir=instance_dir)
  File "/Users/.../lib/python3.6/site-packages/glyphsLib/builder/__init__.py", line 104, in to_designspace
    return builder.designspace
  File "/Users/.../lib/python3.6/site-packages/glyphsLib/builder/builders.py", line 211, in designspace
    self.to_designspace_axes()
  File "/Users/.../lib/python3.6/site-packages/glyphsLib/builder/axes.py", line 201, in to_designspace_axes
    minimum = min(mapping)
TypeError: '<' not supported between instances of 'str' and 'int'
```

@MrBrezina: can you please provide a test file? Maybe the one you used, stripped of all glyphs and miscellaneous data.

**Comment by MrBrezina** [comment]
We have just sent the file to @anthrotype with a different issue. Feel free to use it.
