### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by guidoferreyra** [googlefonts/glyphsLib#612]
Hi, when trying to use fontmake or glyphs2ufo, I get the following error, I tried to find whats the problem but I couldn’t sorted it out. When exporting from glyphs is working fine.

I’m not sure if I can provide the file since its not mine, but If you can point me in a direction where to look for posible issues I would be really glad.

Below the outputed traceback.

Best.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/glyphs2ufo", line 8, in <module>
    sys.exit(_glyphs2ufo_entry_point())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/cli.py", line 228, in _glyphs2ufo_entry_point
    return main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/cli.py", line 189, in main
    return options.func(options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/cli.py", line 220, in glyphs2ufo
    ufo_module=__import__(options.ufo_module),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/__init__.py", line 104, in build_masters
    font = GSFont(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/classes.py", line 3653, in __init__
    p.parse_into_object(self, fp.read())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 63, in parse_into_object
    i = self._parse_dict_into_object(res, text, 1)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/parser.py", line 125, in _parse
    value = self.current_type(value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/types.py", line 129, in __init__
    self.value = self.fromString(value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/glyphsLib/types.py", line 96, in fromString
    return [parse_float_or_int(i) for i in self.regex.match(src).groups()]
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by guidoferreyra** [comment]
Sorry just found that this has already been reported here https://github.com/googlefonts/glyphsLib/pull/447
Should I close this issue?

**Comment by madig** [comment]
If it is indeed the same issue, yes. There is a PR to fix it, but it is incomplete and seemingly abandoned.

**Comment by schriftgestalt** [comment]
The pull requires was fine back when I send it but now it is probably broken. I currently don’t have time to look into this.
