### ISSUE TITLE
Can't handle empty glyph name

### ISSUE THREAD

**Issue by madig** [googlefonts/glyphsLib#638]
I.e. a `glyphname = "";` in the .glyphs file.

```
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\glyphs2ufo.exe\__main__.py", line 7, in <module>
  File "c:\program files\python38\lib\site-packages\glyphsLib\cli.py", line 228, in _glyphs2ufo_entry_point
    return main(args)
  File "c:\program files\python38\lib\site-packages\glyphsLib\cli.py", line 189, in main
    return options.func(options)
  File "c:\program files\python38\lib\site-packages\glyphsLib\cli.py", line 208, in glyphs2ufo
    glyphsLib.build_masters(
  File "c:\program files\python38\lib\site-packages\glyphsLib\__init__.py", line 139, in build_masters
    source.font.save(ufo_path)
  File "c:\program files\python38\lib\site-packages\ufoLib2\objects\font.py", line 546, in save
    self.write(writer, saveAs=saveAs)
  File "c:\program files\python38\lib\site-packages\ufoLib2\objects\font.py", line 481, in write
    self.layers.write(writer, saveAs=saveAs)
  File "c:\program files\python38\lib\site-packages\ufoLib2\objects\layerSet.py", line 311, in write
    layer.write(glyphSet, saveAs=saveAs)
  File "c:\program files\python38\lib\site-packages\ufoLib2\objects\layer.py", line 328, in write
    glyphSet.writeGlyph(
  File "c:\program files\python38\lib\site-packages\fontTools\ufoLib\glifLib.py", line 455, in writeGlyph
    fileName = self.glyphNameToFileName(glyphName, self._existingFileNames.values())
  File "c:\program files\python38\lib\site-packages\fontTools\ufoLib\glifLib.py", line 573, in glyphNameToFileName
    return userNameToFileName(glyphName, existing=existingFileNames, suffix=".glif")
  File "c:\program files\python38\lib\site-packages\fontTools\ufoLib\filenames.py", line 76, in userNameToFileName
    if not prefix and userName[0] == ".":
IndexError: string index out of range
```

**Comment by khaledhosny** [comment]
The failure is in ufoLib, so it is ufoLib that can’t handle empty glyph names, no?

**Comment by madig** [comment]
Hm! https://unifiedfontobject.org/versions/ufo3/glyphs/contents.plist/ says

> Glyph names may contain any character except they must not contain control characters. They may be any length. Glyph names must be unique within the layer.

So ufoLib should indeed be fixed.
