### ISSUE TITLE
ufo2glyphs unhandled AttributeError: 'MarkClassName' object has no attribute 'glyphclass'

### ISSUE THREAD

**Issue by DavidRaymond** [googlefonts/glyphsLib#694]
When running ufo2glyphs I'm seeing the following traceback:
```Traceback (most recent call last):
  File "/home/david/src/glyphsLib/Lib/glyphsLib/builder/features.py", line 595, in _process_glyph_class_definition
    if st.glyphs.original:
AttributeError: 'MarkClassName' object has no attribute 'original'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ufo2glyphs", line 11, in <module>
    load_entry_point('glyphsLib', 'console_scripts', 'ufo2glyphs')()
  File "/home/david/src/glyphsLib/Lib/glyphsLib/cli.py", line 293, in _ufo2glyphs_entry_point
    return main(args)
  File "/home/david/src/glyphsLib/Lib/glyphsLib/cli.py", line 189, in main
    return options.func(options)
  File "/home/david/src/glyphsLib/Lib/glyphsLib/cli.py", line 266, in ufo2glyphs
    font = glyphsLib.to_glyphs(
  File "/home/david/src/glyphsLib/Lib/glyphsLib/builder/__init__.py", line 145, in to_glyphs
    return builder.font
  File "/home/david/src/glyphsLib/Lib/glyphsLib/builder/builders.py", line 749, in font
    self.to_glyphs_features()
  File "/home/david/src/glyphsLib/Lib/glyphsLib/builder/features.py", line 298, in to_glyphs_features
    _to_glyphs_features(
  File "/home/david/src/glyphsLib/Lib/glyphsLib/builder/features.py", line 317, in _to_glyphs_features
    processor.to_glyphs(font)
  File "/home/david/src/glyphsLib/Lib/glyphsLib/builder/features.py", line 496, in to_glyphs
    self._process_file()
  File "/home/david/src/glyphsLib/Lib/glyphsLib/builder/features.py", line 508, in _process_file
    or self._process_glyph_class_definition()
  File "/home/david/src/glyphsLib/Lib/glyphsLib/builder/features.py", line 612, in _process_glyph_class_definition
    elements.append("@" + st.glyphs.glyphclass.name)
AttributeError: 'MarkClassName' object has no attribute 'glyphclass'
```
This can be reproduced by running ufo2glyphs against [DoulosSIL-Regular.ufo](https://github.com/silnrsi/font-doulos/tree/master/source/DoulosSIL-Regular.ufo)

It seems to be triggered by uses a mark class as a glyph class (line 2393: `@c_u_diacs = @_U;` in features.fea.

We believe this is valid fea code - and it is handled OK by the fonttools fea compiler.

**Comment by anthrotype** [comment]
thanks for the bug.

I'm actually not sure what the `except:` clause of the first `try` block below is trying to catch (where the comment says `# Single class`):

https://github.com/googlefonts/glyphsLib/blob/86cbeb56e4c3b26a8c1d5a6fe8de40b3c936b54c/Lib/glyphsLib/builder/features.py#L594-L612

I think that line 612 is triggered because `MarkClassName` object does not have a `original` attribute.
A fix could be to explicitly check for `if hasattr(st.glyphs, "original") and st.glyphs.original` at line 595, so that it falls back to the `else:` clause (where `elements = st.glyphSet()` should work for `MarkClassName`)

Maybe @belluzj can take a look?

**Comment by nrsiward** [comment]
FWIW, you can fix this particular case by adding a `try` clause at the top of the `for` loop:

```
for glyph in st.glyphs.original:
    try: # added try clause
        # Class name (MarkClass object)
        elements.append("@" + glyph.markClass.name)
    except:
        try: # originally the first try clause
            # Class name (GlyphClassName object)
            elements.append("@" + glyph.glyphclass.name)
```

**Comment by anthrotype** [comment]
would you like to send a PR?

**Comment by nrsiward** [comment]
The code shown in the Jul 5 comment does not handle the case where a mark class is being used as a glyph class. In addition to the change I suggested on Jul 14, an additional `except` clause is needed to handle another case where this can happen. The former handles `@cu = [@cU]`. The latter case handles `@cu = @cU`.

>I'm actually not sure what the except: clause of the first try block below is trying to catch

It's trying to catch the case where `st.glyphs` does not have an `original` attribute. The same condition that `if hasattr(st.glyphs, "original")` is testing for. So the code to handle that case should go in that exception handler.

> I think that line 612 is triggered because `MarkClassName` object does not have a `original` attribute.

That case can be handled in a way that matches the style of this code by adding another `try` block

See PR #782

**Comment by anthrotype** [comment]
While adding a test for #782, I noticed that when rountripping back with glyphs2ufo, the order of the glyph classes and mark classes changes; the former are written first, then the latter (because font.classes are serialized before font.featurePrefixes in builder/features.py:

https://github.com/googlefonts/glyphsLib/blob/df8d40763e684dd1efb78ec4504e01490a39d529/Lib/glyphsLib/builder/features.py#L259-L261

... leading to feature code that can't be correctly parsed because `@_U` is only defined later on 

```
E         + @c_u_diacs = [ @_U
E         + ];
E         +
E           markClass CombBreve_Macron <anchor -700 1000> @_U;
E           markClass CombGraphemeJoiner <anchor 0 0> @_U;
E         - @c_u_diacs = @_U;

```

Globally changing the order between font.featurePrefixes and font.classes could lead to other unwanted changes so I'm not sure what to do.
