### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by jpt** [googlefonts/glyphsLib#744]
I'm not quite sure what's causing this. It happens when running `to_designspace`. I'm running the latest glyphsLib, which I was able to test on simpler (I added a single glyph just to test) Glyphs 2 and Glyphs 3 files without issue. Same result with glyphsLib and glyphs2ufo.

While troubleshooting, all I can say for sure is that if I delete one problematic master (seemingly - it's not causing any issues in Glyphs itself), out of six, and save as a Glyphs Version 2 format file, it doesn't have the same problem and is able to read the file.

Any ideas on what to look for? I wonder if there is just some poorly formed data somewhere in the file, but Glyphs itself isn't having issues (nor is FontLab 7's Glyphs-handling capabilities)

```
Traceback (most recent call last):
  File "/Users/tribby/projects/ufo-conv-test/conv.py", line 3, in <module>
    font = GSFont("test.glyphs")
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/classes.py", line 3698, in __init__
    p.parse_into_object(self, fp.read())
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 63, in parse_into_object
    i = self._parse_dict_into_object(res, text, 1)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/parser.py", line 125, in _parse
    value = self.current_type(value)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/types.py", line 129, in __init__
    self.value = self.fromString(value)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/types.py", line 96, in fromString
    return [parse_float_or_int(i) for i in self.regex.match(src).groups()]
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by jpt** [comment]
Aha, it's being caused by the existence of manual TrueType hints on that master, it hadn't occurred to me. If hinting is not supported it might be worthwhile to introduce a more explicit error?
