### ISSUE TITLE
in 6.0.1, fontmake seems to work on but glyphs2ufo doesn't

### ISSUE THREAD

**Issue by jpt** [googlefonts/glyphsLib#758]
I'm having an issue trying to use glyphs2ufo on a Glyphs 3 file — I'm not sure what's causing the issue exactly, I was surprised to see that fontmake can handle the file but glyphs2ufo can't. (could it be a config issue on my end? I tried removing existing glyphsLib and re-installing from this repo as well as pip).

I tried removing hinting, brace layers, features, and a following a few other suspicions with no luck. deleting all glyphs except the letter `A` did work, so I don't think it's a structural problem with the file itself. unfortunately I can't share the file, so I know this is an annoyingly non-reproducible issue to open, but I'm happy to keep trying to diagnose if anyone has any hunches about what I should try first, short of deleting all 1500 glyphs one at a time 😅 

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/__main__.py", line 22, in <module>
    sys.exit(glyphsLib.cli.main())
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/cli.py", line 205, in main
    return options.func(options)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/cli.py", line 224, in glyphs2ufo
    glyphsLib.build_masters(
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/__init__.py", line 120, in build_masters
    designspace = to_designspace(
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/builder/__init__.py", line 123, in to_designspace
    return builder.designspace
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/builder/builders.py", line 345, in designspace
    list(self.masters)  # Make sure that the UFOs are built
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/builder/builders.py", line 227, in masters
    self.to_ufo_layers()
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/builder/builders.py", line 291, in to_ufo_layers
    self.to_ufo_glyph(ufo_glyph, layer, glyph)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/builder/glyph.py", line 279, in to_ufo_glyph
    self.to_ufo_hints(ufo_glyph, layer)
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/builder/hints.py", line 37, in to_ufo_hints
    elif val is not None and not any(v is None for v in val):
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/builder/hints.py", line 37, in <genexpr>
    elif val is not None and not any(v is None for v in val):
  File "/usr/local/lib/python3.9/site-packages/glyphsLib/types.py", line 106, in __getitem__
    assert isinstance(self.value, list) and len(self.value) == self.dimension
AssertionError
```

**Comment by jpt** [comment]
oh wait, I do have a font I can share that is giving me the same error, hadn't tried with Barlow (which is currently undergoing some surgery, figured it would fail for other reasons) - this file produces exactly the same error: https://github.com/jpt/barlow/blob/8cb280c71f29f5cde3375a4394ae5b190030750b/sources/Barlow.glyphs

**Comment by jpt** [comment]
aha, I've been able to reproduce. two things must be true in order for `glyphs2ufo` to run: `--minimal` must be passed as an argument, and there must not be any TrueType hints present in the font. 

I am not sure if this is a feature or a bug, so I'll leave it open (at the least, either documentation of this behavior, or warnings for either scenario — not using `--minimal` or having hints present — would be preferable to the error currently being produced).

dreaming of a glyphs2VTTlib...
