### ISSUE TITLE
Crashes with TrueType-hinted Glyphs file

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/glyphsLib#817]
I get crashes on nearly all my TrueType-hinted Glyphs files when trying to build fonts with fontmake, or converting them to UFO.

The problem is somewhere in the parsing of the hints.

It seems the values of the TrueType hint properties `origin`, `other1`, `other2`, and `target` are parsed as `Point`s when in reality they are references to a node by contour index and node index, e.g. in this hint:

```
{
horizontal = 1;
options = 4;
origin = (1,3);
target = (1,0);
type = TTStem;
},
```

(this at least doesn't crash glyphs2ufo), or, more problematic, they reference a contour index, node index, and up to two other parameters, which are used when points not present in PostScript outlines are hinted, or points which appear only after removing overlaps. Example:

```
{
horizontal = 1;
options = 4;
origin = (0,3,1,0);
other1 = (0,3,0);
target = (0,3);
type = TTInterpolate;
},
```

Georg told me that a 2-tuple refers to a node (path index, node index), a 3-tuple refers to an inflection or handle, and a 4-tuple to an intersection. These can appear on all of `origin`, `other1`, `other2`, and `target`.

I've looked at the hint parsing code, but I can't in a reasonable amount of time figure out how to support all those notations.

I've attached a file that uses all kinds of TrueType hints and custom parameters that are available in G3.

[TrueTypeHintingV3.glyphs.zip](https://github.com/googlefonts/glyphsLib/files/9724959/TrueTypeHintingV3.glyphs.zip)

**Comment by anthrotype** [comment]
Thanks. I wonder how are these TrueType hints represented in the Glyphs Python API. E.g. those specific variable size tuples are they parsed into some class with accessor fields, or are they exposed as bare tuples of ints

**Comment by anthrotype** [comment]
also, could you copy/paste in here the specific traceback from the crash, may help debugging

**Comment by jenskutilek** [comment]
> Thanks. I wonder how are these TrueType hints represented in the Glyphs Python API. E.g. those specific variable size tuples are they parsed into some class with accessor fields, or are they exposed as bare tuples of ints

We're far into undocumented territory here ;)

`GSHint.originNode` has type `GSNode` or `GSHandle` pointing to the actual node or handle object, as per the Glyphs Python API docs;

but closer to the contents of the Glyphs file is this undocumented method:

`GSHint.originIndex()` returns an `NSIndexPath`, e.g.

```
<NSIndexPath: 0xb885a174660c3a19> {length = 4, path = 0 - 3 - 1 - 0}
```

Same for `GSHint.targetIndex()`, `GSHint.otherIndex1()`, and `GSHint.otherIndex2()`.

**Comment by jenskutilek** [comment]
This is the traceback from the attached file:

```
$ glyphs2ufo TrueTypeHintingV3.glyphs
Traceback (most recent call last):
  File "/Users/jens/Documents/Schriften/Variable-Fonts/venv/bin/glyphs2ufo", line 8, in <module>
    sys.exit(_glyphs2ufo_entry_point())
  File "/Users/jens/Code/glyphsLib/Lib/glyphsLib/cli.py", line 259, in _glyphs2ufo_entry_point
    return main(args)
  File "/Users/jens/Code/glyphsLib/Lib/glyphsLib/cli.py", line 218, in main
    return options.func(options)
  File "/Users/jens/Code/glyphsLib/Lib/glyphsLib/cli.py", line 237, in glyphs2ufo
    glyphsLib.build_masters(
  File "/Users/jens/Code/glyphsLib/Lib/glyphsLib/__init__.py", line 120, in build_masters
    designspace = to_designspace(
  File "/Users/jens/Code/glyphsLib/Lib/glyphsLib/builder/__init__.py", line 123, in to_designspace
    return builder.designspace
  File "/Users/jens/Code/glyphsLib/Lib/glyphsLib/builder/builders.py", line 325, in designspace
    list(self.masters)  # Make sure that the UFOs are built
  File "/Users/jens/Code/glyphsLib/Lib/glyphsLib/builder/builders.py", line 202, in masters
    self.to_ufo_layers()  # below!
  File "/Users/jens/Code/glyphsLib/Lib/glyphsLib/builder/builders.py", line 267, in to_ufo_layers
    self.to_ufo_glyph(ufo_glyph, layer, glyph)  # .glyph
  File "/Users/jens/Code/glyphsLib/Lib/glyphsLib/builder/glyph.py", line 144, in to_ufo_glyph
    self.to_ufo_hints(ufo_glyph, layer)  # .hints
  File "/Users/jens/Code/glyphsLib/Lib/glyphsLib/builder/hints.py", line 35, in to_ufo_hints
    elif val is not None and not any(v is None for v in val):
  File "/Users/jens/Code/glyphsLib/Lib/glyphsLib/builder/hints.py", line 35, in <genexpr>
    elif val is not None and not any(v is None for v in val):
  File "/Users/jens/Code/glyphsLib/Lib/glyphsLib/types.py", line 106, in __getitem__
    assert isinstance(self.value, list) and len(self.value) == self.dimension
AssertionError
```

**Comment by jenskutilek** [comment]
> i think this is where those plist arrays get converted into a Point:
> 
> https://github.com/googlefonts/glyphsLib/blob/d6502a8d93ad28676903091c9e075dc912bb54e2/Lib/glyphsLib/classes.py#L2722
> 
> and Point expects exactly two values, so it crashes
> 
> https://github.com/googlefonts/glyphsLib/blob/d6502a8d93ad28676903091c9e075dc912bb54e2/Lib/glyphsLib/types.py#L119

`origin`, `other1`,` other2` must be handled similarly to `target`. But that still doesn't solve that all but the first two values of each field are discarded.

**Comment by jenskutilek** [comment]
Correction: The additional values are not discarded, but the dimension check of the "vector" fails for objects containing them.

**Comment by anthrotype** [comment]
re NSIndexPath => https://developer.apple.com/documentation/foundation/nsindexpath

**Comment by anthrotype** [comment]
thanks Georg, got a link?

**Comment by schriftgestalt** [comment]
Not online, yet. It just says that those properties are NSIndexPath.

And I just added a few lines to Glyphs file spec: https://github.com/schriftgestalt/GlyphsSDK/blob/Glyphs3/GlyphsFileFormat/GlyphsFileFormatv3.md
