### ISSUE TITLE
Variable-CFF2 from Glyphs3

### ISSUE THREAD

**Issue by kostictype** [googlefonts/glyphsLib#826]
I'm trying to use fontmake to export Variable-CFF2 from a Glyphs 3 file. This is all I get:

```
fontmake -g AllotropeItalic14-VAR.glyphs -o variable-cff2
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "AllotropeItalic14-VAR.glyphs" file into <GSFont>
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/fontmake/__main__.py", line 620, in main
    project.run_from_glyphs(inputs.glyphs_path, **args)
  File "/usr/local/lib/python3.10/site-packages/fontmake/font_project.py", line 775, in run_from_glyphs
    designspace_path = self.build_master_ufos(
  File "/usr/local/lib/python3.10/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/fontmake/font_project.py", line 191, in build_master_ufos
    designspace = glyphsLib.to_designspace(
  File "/usr/local/lib/python3.10/site-packages/glyphsLib/builder/__init__.py", line 123, in to_designspace
    return builder.designspace
  File "/usr/local/lib/python3.10/site-packages/glyphsLib/builder/builders.py", line 327, in designspace
    self.to_designspace_sources()  # .sources
  File "/usr/local/lib/python3.10/site-packages/glyphsLib/builder/sources.py", line 40, in to_designspace_sources
    _to_designspace_source_layer(self)
  File "/usr/local/lib/python3.10/site-packages/glyphsLib/builder/sources.py", line 159, in _to_designspace_source_layer
    key = (layer.name, tuple(layer._brace_coordinates()))
  File "/usr/local/lib/python3.10/site-packages/glyphsLib/classes.py", line 3796, in _brace_coordinates
    return [float(c) for c in coordinates.split(",")]
  File "/usr/local/lib/python3.10/site-packages/glyphsLib/classes.py", line 3796, in <listcomp>
    return [float(c) for c in coordinates.split(",")]
ValueError: could not convert string to float: ' 72 off'
```
What am I doing wrong?

**Comment by khaledhosny** [comment]
How did you install glyphsLib/fontmake? You seem to be using an old version that does not support Glyphs 3 files.

**Comment by kostictype** [comment]
> How did you install glyphsLib/fontmake? You seem to be using an old version that does not support Glyphs 3 files.

I installed fontmake with pip. Then I tried the upgrade with `pip3 install -U fontmake`. I just checked, the version is 3.4.0

**Comment by kostictype** [comment]
Sorry, I have no idea what I'm doing (zero coding knowledge), this is what I got:
```
Requirement already satisfied: glyphsLib in /usr/local/lib/python3.10/site-packages (6.1.0)
Requirement already satisfied: ufoLib2>=0.6.2 in /usr/local/lib/python3.10/site-packages (from glyphsLib) (0.13.1)
Requirement already satisfied: fonttools[ufo,unicode]>=4.33.0 in /usr/local/lib/python3.10/site-packages (from glyphsLib) (4.38.0)
Requirement already satisfied: openstep-plist>=0.3.0 in /usr/local/lib/python3.10/site-packages (from glyphsLib) (0.3.0)
Requirement already satisfied: unicodedata2>=14.0.0 in /usr/local/lib/python3.10/site-packages (from fonttools[ufo,unicode]>=4.33.0->glyphsLib) (14.0.0)
Requirement already satisfied: fs<3,>=2.2.0 in /usr/local/lib/python3.10/site-packages (from fonttools[ufo,unicode]>=4.33.0->glyphsLib) (2.4.16)
Requirement already satisfied: attrs>=20.1.0 in /usr/local/lib/python3.10/site-packages (from ufoLib2>=0.6.2->glyphsLib) (22.1.0)
Requirement already satisfied: six~=1.10 in /usr/local/lib/python3.10/site-packages (from fs<3,>=2.2.0->fonttools[ufo,unicode]>=4.33.0->glyphsLib) (1.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/site-packages (from fs<3,>=2.2.0->fonttools[ufo,unicode]>=4.33.0->glyphsLib) (65.4.1)
Requirement already satisfied: appdirs~=1.4.3 in /usr/local/lib/python3.10/site-packages (from fs<3,>=2.2.0->fonttools[ufo,unicode]>=4.33.0->glyphsLib) (1.4.4)
```

**Comment by khaledhosny** [comment]
Sorry for the noise then. I’m afraid someone with access to the font file will need to debug this. It looks like one of the brace layers has coordinates that glyphsLib does not know how to handle, namely this ` 72 off` looks suspicious as there should be only numbers here (unless it is some extended syntax glyphsLib does not know about).

**Comment by kostictype** [comment]
Hey, thank you for the help, I appreciate any suggestion. I'll have a look at the brace layers.

**Comment by kostictype** [comment]
Could it be some bug with the brace layers because the file was formed as Glyphs2 (couple of years ago) then imported and worked on in Glyphs3?

**Comment by kostictype** [comment]
> Sorry for the noise then. I’m afraid someone with access to the font file will need to debug this. It looks like one of the brace layers has coordinates that glyphsLib does not know how to handle, namely this ` 72 off` looks suspicious as there should be only numbers here (unless it is some extended syntax glyphsLib does not know about).

You were correct! I found and deleted old brace layers that were deactivated e.g. {275, 72 OFF} but left among other layers. now I have a different error message:
`fontmake: Error: In 'AllotropeItalic14-VF.glyphs' -> 'master_ufo/AllotropeItalic-Italic.designspace': Generating fonts from Designspace failed: Locations must be unique.`
